export const WRITE_JOURNAL = 'WRITE_JOURNAL';
export const CLEAN_JOURNAL = 'CLEAN_JOURNAL';

export const GET_DATAJOURNAL = 'GET_DATAJOURNAL';
export const MODIFIED_DATAJOURNAL = 'MODIFIED_DATAJOURNAL';
export const DELETE_DATAJOURNAL = 'DELETE_DATAJOURNAL';
export const CLEAN_DATAJOURNAL = 'CLEAN_DATAJOURNAL';

export const GET_DATAORDER = 'GET_DATAORDER';
export const MODIFIED_DATAORDER = 'MODIFIED_DATAORDER';
export const DELETE_DATAORDER = 'DELETE_DATAORDER';
export const CLEAN_DATAORDER = 'CLEAN_DATAORDER';

export const PROFILE_GET_DATAJOURNAL = 'PROFILE_GET_DATAJOURNAL';
export const PROFILE_MODIFIED_DATAJOURNAL = 'PROFILE_MODIFIED_DATAJOURNAL';
export const PROFILE_DELETE_DATAJOURNAL = 'PROFILE_DELETE_DATAJOURNAL';
export const PROFILE_CLEAN_DATAJOURNAL = 'PROFILE_CLEAN_DATAJOURNAL';

export const PROFILE_GET_DATAORDER = 'PROFILE_GET_DATAORDER';
export const PROFILE_MODIFIED_DATAORDER = 'PROFILE_MODIFIED_DATAORDER';
export const PROFILE_DELETE_DATAORDER = 'PROFILE_DELETE_DATAORDER';
export const PROFILE_CLEAN_DATAORDER = 'PROFILE_CLEAN_DATAORDER';

export const GET_CARTITEM = 'GET_CARTITEM';
export const GET_INFOITEM = 'GET_INFOITEM';
export const GET_ITEMCOUNT = 'GET_ITEMCOUNT';
export const DELETE_CARTITEM = 'DELETE_CARTITEM';
export const QUANTITY_CART = 'QUANTITY_CART';
export const CLEAN_CART = 'CLEAN_CART';
